/**
 * index.esm.js
 * Esm Custom File.
 * This is not an autogenerated file.
 */
import AbolishEsm from "./index.esm-bundled.js";

const { Abolish, Schema, Rule } = AbolishEsm;

export { Abolish, Schema, Rule };
